import axios from 'axios';
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link';
import { useEffect, useState } from 'react'

import Parser from 'rss-parser';

let parser = new Parser({
  timeout: 30000,

});


const Home: NextPage = (props: any) => {
  const { feed } = props;
  const [posts, setPosts] = useState([]);
  const [keyword, setKeyword] = useState('');

  const [filterWordList, setFilterWordList] = useState(['']);

  useEffect(() => {
    const words = keyword.split(',')
    setFilterWordList(words);
  }, [keyword])




  return (
    <div >
      <Head>
        <title>点道信息员</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-full h-screen  flex flex-row'>

        <div className='  h-full w-full'>
          <div className=' bg-slate-200  p-6 flex flex-col justify-center items-center font-mono'>
            <h1 className='w-full font-black text-2xl  text-slate-700 mt-10 '>点道信息员</h1>
            <div className='w-full my-4'>
              <input type="text" className=' bg-gray-100 p-2 rounded-lg' value={keyword} onChange={(e) => {
                setKeyword(e.target.value)
              }} />
            </div>
          </div>
          <div className=' p-4 h-screen overflow-scroll'>
            {
              filterWordList.map((word: string) => {
                return feed.items.map((item: any, key: any) => {
                  if (item.title.includes(word)) {
                    // eslint-disable-next-line react/jsx-key
                    // eslint-disable-next-line @next/next/link-passhref
                    return <Link href={item.link} key={key}>
                      <div key={key} className='  py-2 px-4 rounded-xl my-2 hover:bg-slate-200 cursor-pointer'>
                        <div className='text-slate-500 m-0'>{item.title}</div>
                        <div className='text-slate-400 font-thin text-sm m-0'>{item.pubDate}</div>
                      </div></Link>
                  }
                })
              })
            }
          </div>
        </div>

      </div>
    </div>
  )
}


Home.getInitialProps = async () => {
  let feed = await parser.parseURL('http://www.people.com.cn/rss/politics.xml');
  console.log(feed.items.length);
  return { feed }
}

export default Home;